# Generated by Django 4.1 on 2022-08-27 16:48

from django.db import migrations, models
import django.db.models.deletion
import semantic_version.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hljs_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_version', semantic_version.django_fields.SemVerField(max_length=200)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SnippetPermissionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete', models.BooleanField()),
                ('edit', models.BooleanField()),
                ('edit_perms', models.BooleanField()),
                ('fork', models.BooleanField()),
                ('rename', models.BooleanField()),
                ('view', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SnippetUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippetperms', to='api_snippets.snippet')),
            ],
        ),
    ]
