# Generated by Django 4.1 on 2022-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_snippets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetuserpermission',
            name='can',
        ),
        migrations.RemoveField(
            model_name='snippetuserpermission',
            name='snippet',
        ),
        migrations.RemoveField(
            model_name='snippetuserpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='anyone_can',
        ),
        migrations.AddField(
            model_name='snippet',
            name='allow_forks',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='allow_view',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SnippetPermissionSet',
        ),
        migrations.DeleteModel(
            name='SnippetUserPermission',
        ),
    ]
