# Generated by Django 4.1 on 2022-08-27 18:06

from django.db import migrations, models
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_snippets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language_version',
            field=semantic_version.django_fields.SemVerField(blank=True, max_length=200, null=True),
        ),
    ]
