# Generated by Django 4.1 on 2022-08-29 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_snippets', '0003_remove_snippetuserpermission_can_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='editors',
            field=models.ManyToManyField(related_name='shared_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
