# Generated by Django 4.1 on 2022-08-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_snippets', '0003_alter_snippet_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippetpermissionset',
            old_name='delete',
            new_name='destroy',
        ),
    ]
