# Generated by Django 4.1 on 2022-08-30 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_snippets', '0004_snippet_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='api_snippets.snippet'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='allow_forks',
            field=models.BooleanField(verbose_name='Anyone can fork'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='allow_view',
            field=models.BooleanField(verbose_name='Anyone can view'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='shared_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
